# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89241cb4e483cb7dc9b0b3be77b3d3d41392ad714f5caa1981efe3d95e08e7d7e74bc5b1622c0a635f6d74bb109607396923c4b6874b9ee984e0d3440f6f4350

test:
  secret_key_base: 52bcc259fc2690993f7534c17c0a81eb32f7ea56d27404528c415045d3c5fd6e708ce1373844e5ff456836ad5969ac11d3fa1dac5c95ac660a5eb9d5f0dd9ae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
